name = "itsmichaela"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "itsmichaela.com/*", zone_name = "itsmichaela.com" },
  { pattern = "www.itsmichaela.com/*", zone_name = "itsmichaela.com" }
]

